{% set name = "awscliv2" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vemel/awscliv2/archive/{{ version }}.tar.gz
  sha256: b7cdade4b7a47acc389fe65a57691481f27c1c385ffdffb60be2725aa6b0416a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - awscliv2 = awscliv2.main:main_cli
    - awsv2 = awscliv2.main:main_cli

requirements:
  build:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  commands:
    - awscliv2 -h
    - awsv2 -h

about:
  home: https://github.com/vemel/awscliv2
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Wrapper for AWS CLI v2
  description: |
    Wrapper for AWS CLI v2 requires a local installation of docker to work

extra:
  recipe-maintainers:
    - ocefpaf
